apiVersion: apps/v1
kind: Deployment
metadata:
  name: verx-app
  labels:
    app.kubernetes.io/name: verx-app
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/name: verx-app
  template:
    metadata:
      labels:
        app.kubernetes.io/name: verx-app
      name: verx-app
    spec:
      securityContext:
        {}
      containers:      

      - name: verx-app
        image: verx-app-image:latest
        env:
        - name: POSTGRES_URL_CONNECTION
          valueFrom:
            secretKeyRef:
              key: POSTGRES_URL_CONNECTION
              name: verx-app-secret
        - name: POSTGRES_TEST_URL_CONNECTION
          valueFrom:
            secretKeyRef:
              key: POSTGRES_TEST_URL_CONNECTION
              name: verx-app-secret
        - name: NODE_ENV
          value: production
        - name: API_VERSION
          value: v1
        - name: PORT
          value: "3000"

        # imagePullPolicy: Always # IfNotPresent
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 9000
          protocol: TCP
        resources:
          requests:
            memory: "128Mi"
            cpu: "50m"
            ephemeral-storage: "10Mi"
          limits:
            memory: "512Mi"
            cpu: "200m"
            ephemeral-storage: "100Mi"
        securityContext:
          # https://kubernetes.io/docs/tasks/configure-pod-container/security-context
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: false
          runAsNonRoot: true
          runAsUser: 50000
          runAsGroup: 50000